server:
  port: 8083
spring:
  application:
    name: pay-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #username: simon
    #password: Simonlll746936!
    #url: jdbc:mysql://47.104.97.234:3306/xuantong?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://118.190.202.65:3306/paydemo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.wmk.paydemo.entity
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log/logback-develop.xml
  #打印数据库sql
  level:
    com.example.demo.dao : debug